### ISSUE TITLE
BST Version 3.2.3 displays Release Info above the Menu briefly when opening the game

### ISSUE THREAD

**Issue by Advent-Seph** [taz030485/BeatSaberTweaks#7]
On Oculus (unsure if this also happens on the Vive), when I launch the game, the release info text hovers above the main menu box before disappearing after a few seconds.

![untitled](https://user-images.githubusercontent.com/34399412/43116987-82868764-8ed8-11e8-8d8b-f5567f851f27.jpg)

I removed all other plugins to be sure, this happens when only Beat Saber Tweaks is installed, so I don't think it's the result of a plugin conflict. I'm on version 3.2.3

**Comment by taz030485** [comment]
I have written a fix for this. It will be in the next version.
